comment:
    resource: "@CommentBundle/Resources/config/routing.yml"
    prefix:   /comment

test:
    resource: "@TestBundle/Controller/"
    type:     annotation
    prefix:   /test

post:
    resource: "@PostBundle/Controller/"
    type:     annotation
    prefix:   /post

app:
    resource: '@AppBundle/Controller/'
    type: annotation
