test:
    resource: "@TestBundle/Controller/"
    type:     annotation
    prefix:   /

post:
    resource: "@PostBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
